refactor according pmd rules
datakaveri/iudx-file-server pull request #135
Opened 2023-04-13 12:31 UTC by ananjaykumar2

* refactor according pmd rules @Priority 3

2023-04-17 03:44 UTC, kailash requested changes

2023-04-17 03:44 UTC, kailash commented on src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
> +          ResponseUrn urn = fromCode(resultTitle);
```suggestion
          ResponseUrn urn = urnFromCode(resultTitle);
```
better to change the method name.

2023-04-26 11:59 UTC, kailash approved these changes

2023-04-26 12:03 UTC, ankitmashu commented
LGTM

2023-04-26 12:04 UTC, merged