License information update
datakaveri/iudx-file-server pull request #154
Opened 2024-03-04 17:48 UTC by sushanthakumar

**PR Description:**
This PR is to update the license information of this project along with its dependencies
License file information in README file is updated accordingly
Project license is updated from MIT to Apache Version 2.0 considering the project use cases and deployment scenarios.

2024-03-04 17:49 UTC, sushanthakumar commented
@swaminathanvasanth @abhi4578 Please have a look

2024-03-05 05:29 UTC, swaminathanvasanth commented on LICENSE
> +
Need to add Immudb <https://github.com/codenotary/immudb/blob/master/LICENSE>

2024-03-05 06:08 UTC, swaminathanvasanth commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Copyright [2024] [IUDX Programme Unit, Society of Innovation and Development, Indian Institute of Science, Bangalore]

2024-03-05 06:09 UTC, swaminathanvasanth requested changes
Add the following: 
L190: Copyright [2024] [IUDX Programme Unit, Society of Innovation and Development, Indian Institute of Science, Bangalore]
L226: Add Immudb <https://github.com/codenotary/immudb/blob/master/LICENSE>

2024-03-05 06:17 UTC, sushanthakumar commented
Ok , will use this

2024-03-06 09:27 UTC, swaminathanvasanth requested changes
dep-licenses: 
L4,L5 are the same

Have updated the excel to include groupID:artifactID for all the Dependant Module/Repository column. Can we update the column as per the reference sheet?

2024-03-11 07:14 UTC, sushanthakumar commented
@swaminathanvasanth @abhi4578 Dependency licenses file updated with all the licenses related to servers and client packages, pls review

2024-03-11 08:29 UTC, swaminathanvasanth approved these changes
LGTM

2024-03-11 11:05 UTC, merged